version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   
    networks:
      rede:
        ipv4_address: 10.11.0.2

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres
    networks:
      rede:
        ipv4_address: 10.11.0.3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST_DB=10.11.0.2
      - USER_DB=root
      - PASSWORD_DB=root
      - NAME_DB=root
      - PORT_DB=5432
    networks:
      rede:
        ipv4_address: 10.11.0.4

networks:
  rede:
    driver: bridge
    ipam:
     config:
       - subnet: 10.11.0.0/16
         gateway: 10.11.0.1
     